e3sm: renamed acme and made it build locally

diff --git a/e3sm b/e3sm
--- a/e3sm
+++ b/e3sm
@@ -6,12 +6,16 @@ rm -rf CMakeFiles/
 rm -f  build.ninja
 rm -f  rules.ninja
 
-export ACME_ROOT=$HOME/code/acme
-export HOMME_ROOT=$ACME_ROOT/components/homme
-export Trilinos_DIR=$HOME/local/opt/trilinos-acme
+export E3SM_ROOT=$HOME/code/e3sm
+export HOMME_ROOT=$E3SM_ROOT/components/homme
+export Trilinos_DIR=$HOME/local/opt/trilinos-fortrilinos
 
 NETCDF_DIR=`spack find -p netcdf | tail -n 1 | awk '{print $2}'`
 NETCDFF_DIR=`spack find -p netcdf-fortran | tail -n 1 | awk '{print $2}'`
+
+[[ "$NETCDF_DIR" == "No" ]] && echo "Spack netcdf package not found" && exit 1
+[[ "$NETCDFF_DIR" == "No" ]] && echo "Spack netcdf-fortran package not found" && exit 1
+
 
 NP=4
 NLEVELS=26
@@ -22,10 +26,11 @@ ARGS=(
 
     -D CMAKE_BUILD_TYPE=RELWITHDEBINFO
 
-    -D BUILD_SHARED_LIBS=ON
+    -D BUILD_SHARED_LIBS=OFF
 
     ### COMPILERS AND FLAGS ###
     -D CMAKE_Fortran_COMPILER=mpif90
+        # -D CMAKE_Fortran_FLAGS="-Wtabs -Wno-unused-variable"
     -D CMAKE_C_COMPILER=mpicc
     -D CMAKE_CXX_COMPILER=mpicxx
     -D ENABLE_OPENMP=OFF
@@ -33,28 +38,25 @@ ARGS=(
 
     ### TPLS ###
     -D HOMME_FIND_BLASLAPACK=ON
+    -D NetCDF_C_PATH="${NETCDF_DIR}"
+    -D NetCDF_Fortran_PATH="${NETCDFF_DIR}"
+        # -D NetCDF_Fortran_INCLUDE_DIR="${NETCDFF_DIR}/include"
     -D WITH_PNETCDF=OFF
-        -D Netcdf_INCLUDE_DIR="${NETCDF_DIR}/include;${NETCDFF_DIR}/include"
-        -D NETCDF_C_INCLUDE_DIR="${NETCDFF_DIR}/include"
-        -D NETCDF_C_LIBRARY="${NETCDF_DIR}/lib/libnetcdf.so"
-        -D Netcdf_LIBRARY="${NETCDF_DIR}/lib/libnetcdf.so"
-        -D NETCDF_Fortran_INCLUDE_DIR="${NETCDFF_DIR}/include"
-        -D NETCDF_Fortran_LIBRARY="${NETCDFF_DIR}/lib/libnetcdff.so"
-        -D NetcdfF_LIBRARY="${NETCDFF_DIR}/lib/libnetcdff.so"
 
     ### PACKAGES CONFIGURATION ###
-    -D BUILD_HOMME_PRIM=ON
+    -D BUILD_HOMME_PREQX=OFF
+    -D BUILD_HOMME_PREQX_ACC=OFF
+    -D BUILD_HOMME_PRIM=OFF
         -D PRIM_NP=$NP
         -D PRIM_PLEV=$NLEVELS
         -D QSIZE_D=$NTRACERS
+    -D BUILD_HOMME_SWEQX=OFF
     -D BUILD_HOMME_SWIM=ON
         -D SWIM_NP=$NP
-    -D BUILD_HOMME_SWEQX=ON
-    -D BUILD_HOMME_PREQX=ON
-    -D BUILD_HOMME_PREQX_ACC=OFF
+    -D BUILD_HOMME_THETA=OFF
 
     # The way baseline works is like this:
-    # 1. Pull a fresh unmodified copy of ACME
+    # 1. Pull a fresh unmodified copy of E3SM
     # 2. Build
     # 3. Run `make baseline` to produce gold baseline
     # 4. Modify soures and use a second build for development
